### PR TITLE
feat: add macos workflow

### PR DESCRIPTION
**Pull request by chenrui333**
relates #19

### CODE REVIEW

**Comment by rrthomas** [comment]
Thanks for putting this together! I see it's still draft, but I'm a bit baffled by a couple of the commits here: the `lib` subdirectory exists and is needed, you can't just remove it from the build.

**Comment by chenrui333** [comment]
@rrthomas actually it has some build issues, you can see the action runs in here, https://github.com/chenrui333/mmv/actions

**Comment by rrthomas** [comment]
Sure, if there's an issue, please report it. As I say, you can't simply build without `lib`.

**Comment by rrthomas** [comment]
I've added a GitHub CI build for Ubuntu and macOS.

**Pull request closed without merging**
